# This compose file is meant to spin up a copy of all supported database vendors + Redis and S3 (Minio).
# For production use see the docker compose file example in the docs:
#     https://docs.directus.io/self-hosted/installation/docker/#docker-compose
#
# ONLY FOR DEBUGGING. THIS IS NOT INTENDED FOR PRODUCTION USE.
#
# Ports:
#   MariaDB:         5102

#
# Credentials:
#   MariaDB:
#     User:          root
#     Password:      secret

version: '3.8'
services:
  maria:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: directus
    ports:
      - "5102:3306"
